### ISSUE TITLE
Enable `type` kwarg without var name

### ISSUE THREAD

**Issue by ghost** [deeprave/django-settings-env#38]
Hi,

your library looks promising for my Django project. 👍 

However, I found that `DEBUG = env(default=False, type=bool)` does not work unless the variable name is also specified (thus, `DEBUG = env("DEBUG", default=False, type=bool)` works). From looking at the code, I think the reason is that the `type` kwarg is not incorporated in `DjangoEnv.__call__`'s if branch `if var is None:` (which results in a `DeferredSetting`). From what I've read, it should be possible to pass `type` along and use `django_env_typemap` either in `DjangoEnv.get` or `DeferredSetting.setting`. The former may be preferable because then `DeferredSetting` does not need to know/access `DjangoEnv.django_env_typemap`, and could look sth. like this:

```python
def get(self, var, default=None, prefix=_USE_DEFAULT_PREFIX, type="str"):
    if type == "str":
        return super().get(self._with_prefix(var, prefix=prefix), default)
    else:
        return self.django_env_typemap[type](
            self, var, default=default, prefix=prefix
        )
```

where the `type` kwarg is passed from `DeferredSetting ._kwargs` in `DeferredSetting.setting`.

---

If there is a good reason to not support this behavior, it should at least be stated in the docs IMO. 

Let me know what you think 😉

**Comment by deeprave** [comment]
Glad you find it useful, and thanks for the bug report.

This was not intentional. All kwargs specified in an implied/deferred setting should be passed into the DefaultSetting instance.
